### ISSUE TITLE
Stream max-lifetime feature moving to server-side & test flakiness

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/otel-arrow#6]
@moh-osman3 Has been working on https://github.com/f5/otel-arrow-adapter/pull/211 which was in-flight when this repository migration began. @lquerel had asked for the mechanism to be configurable on the server side, which made more sense to @moh-osman3 and me after we studied the problem further. @moh-osman3 will rebase that work into this repository.

Meanwhile, there is one flaky test that I will ignore to move forward with the migration.

**Comment by jmacd** [comment]
Failure is seen in #4.

```
=== RUN   TestStreamGracefulShutdown
panic: test timed out after 10m0s

goroutine 5200 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.19.12/x64/src/testing/testing.go:2036 +0x8e
created by time.goFunc
	/opt/hostedtoolcache/go/1.19.12/x64/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc0004b0000, {0xf7deba?, 0x518865?}, 0xfc1370)
	/opt/hostedtoolcache/go/1.19.12/x64/src/testing/testing.go:1494 +0x37a
testing.runTests.func1(0xc0001fdb60?)
	/opt/hostedtoolcache/go/1.19.12/x64/src/testing/testing.go:1846 +0x6e
testing.tRunner(0xc0004b0000, 0xc00045fcd8)
	/opt/hostedtoolcache/go/1.19.12/x64/src/testing/testing.go:1446 +0x10b
testing.runTests(0xc0001ebf40?, {0x1851380, 0x11, 0x11}, {0x7f2c9b1375b8?, 0x40?, 0x1861940?})
	/opt/hostedtoolcache/go/1.19.12/x64/src/testing/testing.go:1844 +0x456
testing.(*M).Run(0xc0001ebf40)
	/opt/hostedtoolcache/go/1.19.12/x64/src/testing/testing.go:1726 +0x5d9
main.main()
	_testmain.go:79 +0x1aa

goroutine 4816 [select, 9 minutes]:
github.com/open-telemetry/otel-arrow/collector/gen/exporter/otlpexporter/internal/arrow.(*healthyTestChannel).onRecv.func1()
	/home/runner/work/otel-arrow/otel-arrow/collector/gen/exporter/otlpexporter/internal/arrow/common_test.go:195 +0x9a
reflect.Value.call({0xe03100?, 0xc0006c2480?, 0xc00056ba00?}, {0xf690dd, 0x4}, {0x18933f8, 0x0, 0x40f45f?})
	/opt/hostedtoolcache/go/1.19.12/x64/src/reflect/value.go:584 +0x8c5
reflect.Value.Call({0xe03100?, 0xc0006c2480?, 0x0?}, {0x18933f8?, 0x4d8816?, 0xe51f00?})
	/opt/hostedtoolcache/go/1.19.12/x64/src/reflect/value.go:368 +0xbc
github.com/golang/mock/gomock.(*Call).DoAndReturn.func1({0x0, 0x0, 0xc0004e86a0?})
	/home/runner/go/pkg/mod/github.com/golang/mock@v1.6.0/gomock/call.go:132 +0x485
github.com/golang/mock/gomock.(*Controller).Call(0xc010b0aa50, {0xee4ce0, 0xc0004e86a0}, {0xf69261, 0x4}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/golang/mock@v1.6.0/gomock/controller.go:251 +0xf7
github.com/open-telemetry/otel-arrow/api/experimental/arrow/v1/mock.(*MockArrowStreamService_ArrowStreamClient).Recv(0xc0004e86a0)
	/home/runner/work/otel-arrow/otel-arrow/api/experimental/arrow/v1/mock/arrow_service_mock.go:129 +0x59
github.com/open-telemetry/otel-arrow/collector/gen/exporter/otlpexporter/internal/arrow.(*Stream).read(0xc0001da1b0, {0xc021050[280](https://github.com/open-telemetry/otel-arrow/actions/runs/5826962689/job/15802016892#step:5:281)?, 0x0?})
	/home/runner/work/otel-arrow/otel-arrow/collector/gen/exporter/otlpexporter/internal/arrow/stream.go:351 +0x35
github.com/open-telemetry/otel-arrow/collector/gen/exporter/otlpexporter/internal/arrow.(*Stream).run(0xc0001da1b0, {0x10f4358?, 0xc021050200?}, 0xc00d07b1b8, {0x0, 0x0, 0x0})
	/home/runner/work/otel-arrow/otel-arrow/collector/gen/exporter/otlpexporter/internal/arrow/stream.go:167 +0x246
github.com/open-telemetry/otel-arrow/collector/gen/exporter/otlpexporter/internal/arrow.(*streamTestCase).start.func1()
	/home/runner/work/otel-arrow/otel-arrow/collector/gen/exporter/otlpexporter/internal/arrow/stream_test.go:84 +0x95
created by github.com/open-telemetry/otel-arrow/collector/gen/exporter/otlpexporter/internal/arrow.(*streamTestCase).start
	/home/runner/work/otel-arrow/otel-arrow/collector/gen/exporter/otlpexporter/internal/arrow/stream_test.go:82 +0xb8

goroutine 4815 [chan receive, 9 minutes]:
github.com/open-telemetry/otel-arrow/collector/gen/exporter/otlpexporter/internal/arrow.(*streamTestCase).get(...)
	/home/runner/work/otel-arrow/otel-arrow/collector/gen/exporter/otlpexporter/internal/arrow/stream_test.go:119
github.com/open-telemetry/otel-arrow/collector/gen/exporter/otlpexporter/internal/arrow.TestStreamGracefulShutdown(0xc000378340?)
	/home/runner/work/otel-arrow/otel-arrow/collector/gen/exporter/otlpexporter/internal/arrow/stream_test.go:149 +0x33b
testing.tRunner(0xc0003784e0, 0xfc1370)
	/opt/hostedtoolcache/go/1.19.12/x64/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.19.12/x64/src/testing/testing.go:1493 +0x35f
FAIL	github.com/open-telemetry/otel-arrow/collector/gen/exporter/otlpexporter/internal/arrow	600.106s
?   	github.com/open-telemetry/otel-arrow/collector/gen/exporter/otlpexporter/internal/arrow/grpcmock	[no test files]
```

**Comment by jmacd** [comment]
See @moh-osman3's investigation in https://github.com/grpc/grpc-go/issues/6504
